[package]
name = "background"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]
build = "build.rs"

[dependencies]
common = { path = "../../Rust/common" }
# common = { git = "https://github.com/manpat/common-rs.git" }
